
CREATE TABLE IF NOT EXISTS xitu_user(
  ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  account VARCHAR(255) DEFAULT NULL,
  password VARCHAR(255) DEFAULT NULL,
  name VARCHAR(255) DEFAULT NULL,
  identity VARCHAR(255) DEFAULT NULL,
  unit VARCHAR(255) DEFAULT NULL,
  job VARCHAR(255) DEFAULT NULL,
  duty VARCHAR(255) DEFAULT NULL,
  major VARCHAR(255) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL,
  phone VARCHAR(255) DEFAULT NULL,
  wechat VARCHAR(255) DEFAULT NULL,
  role VARCHAR(255) DEFAULT NULL,
  stamp VARCHAR(255) DEFAULT NULL
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS xitu_item(
  ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  service VARCHAR(255) DEFAULT NULL,
  item VARCHAR(255) DEFAULT NULL
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS xitu_price(
  ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) DEFAULT NULL,
  description VARCHAR(255) DEFAULT NULL,
  unit VARCHAR(255) DEFAULT NULL,
  price VARCHAR(255) DEFAULT NULL,
  floating VARCHAR(255) DEFAULT NULL,
  update_time VARCHAR(255) DEFAULT NULL
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS xitu_patent(
  ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) DEFAULT NULL,
  subject TEXT DEFAULT NULL,
  person VARCHAR(500) DEFAULT NULL,
  creator VARCHAR(500) DEFAULT NULL,
  applytime VARCHAR(255) DEFAULT NULL,
  publictime VARCHAR(255) DEFAULT NULL,
  applyyear VARCHAR(255) DEFAULT NULL,
  publicyear VARCHAR(255) DEFAULT NULL,
  ptype VARCHAR(255) DEFAULT NULL,
  description TEXT DEFAULT NULL,
  claim TEXT DEFAULT NULL,
  publicnumber VARCHAR(255) DEFAULT NULL,
  applynumber VARCHAR(255) DEFAULT NULL,
  ipc VARCHAR(1000) DEFAULT NULL,
  cpc VARCHAR(255) DEFAULT NULL,
  piroryear VARCHAR(255) DEFAULT NULL,
  country VARCHAR(255) DEFAULT NULL,
  lawstatus VARCHAR(255) DEFAULT NULL,
  now INT DEFAULT 0
) DEFAULT CHARSET=utf8;




